services:
  - type: web
    name: gpt_session_restored
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class aiohttp.GunicornWebWorker bot:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false